//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class parameters {
    
    private parametersChannel[] channelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("channel")]
    public parametersChannel[] channel {
        get {
            return this.channelField;
        }
        set {
            this.channelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class parametersChannel {
    
    private int hardwareChannelField;
    
    private parametersChannelDirection directionField;
    
    private parametersChannelSpeed speedField;
    
    private parametersChannelLabel[] labelField;
    
    public parametersChannel() {
        this.speedField = parametersChannelSpeed.high;
    }
    
    /// <remarks/>
    public int hardwareChannel {
        get {
            return this.hardwareChannelField;
        }
        set {
            this.hardwareChannelField = value;
        }
    }
    
    /// <remarks/>
    public parametersChannelDirection direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(parametersChannelSpeed.high)]
    public parametersChannelSpeed speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("label")]
    public parametersChannelLabel[] label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum parametersChannelDirection {
    
    /// <remarks/>
    incoming,
    
    /// <remarks/>
    outgoing,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum parametersChannelSpeed {
    
    /// <remarks/>
    high,
    
    /// <remarks/>
    low,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class parametersChannelLabel {
    
    private int labelDecimalField;
    
    private bool labelDecimalFieldSpecified;
    
    private int labelOctalField;
    
    private bool labelOctalFieldSpecified;
    
    private parametersChannelLabelSdi sdiField;
    
    private int transferTypeField;
    
    private int periodField;
    
    private bool createTimestampChannelField;
    
    private bool createSDIChannelField;
    
    private bool createSSMChannelField;
    
    private bool createParityChannelField;
    
    private parametersChannelLabelParameter[] parameterField;
    
    public parametersChannelLabel() {
        this.sdiField = parametersChannelLabelSdi.All;
        this.transferTypeField = 0;
        this.periodField = 1000;
        this.createTimestampChannelField = false;
        this.createSDIChannelField = false;
        this.createSSMChannelField = false;
        this.createParityChannelField = false;
    }
    
    /// <remarks/>
    public int labelDecimal {
        get {
            return this.labelDecimalField;
        }
        set {
            this.labelDecimalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool labelDecimalSpecified {
        get {
            return this.labelDecimalFieldSpecified;
        }
        set {
            this.labelDecimalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int labelOctal {
        get {
            return this.labelOctalField;
        }
        set {
            this.labelOctalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool labelOctalSpecified {
        get {
            return this.labelOctalFieldSpecified;
        }
        set {
            this.labelOctalFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(parametersChannelLabelSdi.All)]
    public parametersChannelLabelSdi sdi {
        get {
            return this.sdiField;
        }
        set {
            this.sdiField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int transferType {
        get {
            return this.transferTypeField;
        }
        set {
            this.transferTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(1000)]
    public int period {
        get {
            return this.periodField;
        }
        set {
            this.periodField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool createTimestampChannel {
        get {
            return this.createTimestampChannelField;
        }
        set {
            this.createTimestampChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool createSDIChannel {
        get {
            return this.createSDIChannelField;
        }
        set {
            this.createSDIChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool createSSMChannel {
        get {
            return this.createSSMChannelField;
        }
        set {
            this.createSSMChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool createParityChannel {
        get {
            return this.createParityChannelField;
        }
        set {
            this.createParityChannelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parameter")]
    public parametersChannelLabelParameter[] parameter {
        get {
            return this.parameterField;
        }
        set {
            this.parameterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum parametersChannelLabelSdi {
    
    /// <remarks/>
    All,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("00")]
    Item00,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("01")]
    Item01,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class parametersChannelLabelParameter {
    
    private parametersChannelLabelParameterEncoding encodingField;
    
    private bool signedField;
    
    private int startBitField;
    
    private int numberOfBitsField;
    
    private double scaleField;
    
    private double offsetField;
    
    private string nameField;
    
    private string unitField;
    
    private double defaultValueField;
    
    public parametersChannelLabelParameter() {
        this.encodingField = parametersChannelLabelParameterEncoding.BNR;
        this.signedField = false;
        this.startBitField = 8;
        this.scaleField = 1D;
        this.offsetField = 0D;
        this.defaultValueField = 0D;
    }
    
    /// <remarks/>
    public parametersChannelLabelParameterEncoding encoding {
        get {
            return this.encodingField;
        }
        set {
            this.encodingField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool signed {
        get {
            return this.signedField;
        }
        set {
            this.signedField = value;
        }
    }
    
    /// <remarks/>
    public int startBit {
        get {
            return this.startBitField;
        }
        set {
            this.startBitField = value;
        }
    }
    
    /// <remarks/>
    public int numberOfBits {
        get {
            return this.numberOfBitsField;
        }
        set {
            this.numberOfBitsField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(1D)]
    public double scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public double defaultValue {
        get {
            return this.defaultValueField;
        }
        set {
            this.defaultValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public enum parametersChannelLabelParameterEncoding {
    
    /// <remarks/>
    BNR,
    
    /// <remarks/>
    BCD,
    
    /// <remarks/>
    Discrete,
}
